"""Retain strict-gate failures rather than promoting favorable interaction scores.
Reporting-only corrections discovered on independent evidence consolidation.
"""
from pathlib import Path
import hashlib,json
S=Path('/mnt/data/egfr_campaign/stage5');records=[]
p=S/'code/compile_evidence.py';before=p.read_text();(S/'logs/compile_evidence_before_final_gate.py.txt').write_text(before)
text=before.replace("'decision':'Retain for further evaluation as conditional pH improvement over matched C00003 parent' if delta>0 else 'Do not promote as a robust pH improvement'", "'decision':('Retain for further evaluation as conditional pH improvement over matched C00003 parent' if all(m['geometry_context_pass'] for m in r['models']) else 'Human pH improvement only: exclude current mouse hypothesis until strict peptide-geometry failure is repaired') if delta>0 else 'Do not promote as a robust pH improvement'")
text=text.replace("'decision':'Retain contact-preserving backbone alternative as unvalidated; no matched thermal or mouse evaluation completed.'", "'decision':'Retain the contact-preserving branch for repair, not this pose for promotion: fixed 1IVO context clash. No matched thermal or mouse evaluation completed.'")
p.write_text(text);records.append({'file':str(p),'old_sha256':hashlib.sha256(before.encode()).hexdigest(),'new_sha256':hashlib.sha256(text.encode()).hexdigest()})
p=S/'code/write_report.py';before=p.read_text();(S/'logs/write_report_before_final_gate.py.txt').write_text(before)
text=before.replace('Those three designs pass the checked human and mouse geometries.', 'H00011 and H00021 pass the checked human and mouse geometries. H00020 has favorable pH scores but fails the strict peptide-geometry check in its mouse model.')
text=text.replace('H00011, H00020, and H00021 pass the checked mouse geometry and retain favorable mouse interaction-energy diagnostics.', 'H00011 and H00021 pass the checked mouse geometry and retain favorable mouse interaction-energy diagnostics. H00020 has favorable interaction diagnostics but its mouse peptide bond at positions 100-101 is 26.30 degrees from trans, beyond the predeclared 25-degree gate. Its local contact/bond-length checks had passed, but that did not establish the stricter peptide criterion. It is not promoted as a passing mouse model; the threshold was not loosened.')
text=text.replace('Retain H00011/H00020/H00021 as conditional pH improvements over the matched C00003-derived parent, not as experimentally established leads.', 'Retain H00011 and H00021 as conditional pH improvements over the matched C00003-derived parent, not as experimentally established leads. H00020 remains a human-pH hypothesis with a failed mouse peptide gate, not a fully geometry-passing candidate.')
text=text.replace('Keep the E106-preserving T branch as an alternative, but do not infer mouse or thermal behavior that was not evaluated.', 'Keep the E106-preserving T branch as an alternative for repair, but the otherwise promising T3070400 and T3080401 poses each clash with the fixed 1IVO context. Do not promote those poses or infer mouse/thermal behavior that was not evaluated.')
p.write_text(text);records.append({'file':str(p),'old_sha256':hashlib.sha256(before.encode()).hexdigest(),'new_sha256':hashlib.sha256(text.encode()).hexdigest()})
(S/'reference/final_reporting_corrections.json').write_text(json.dumps({'corrections':records,'reason':'Strict independent peptide/context gates, not changes to scientific data or thresholds','H00020_mouse_omega_deg':-153.6972230638966,'trans_deviation_deg':26.3027769361034,'predeclared_maximum_deviation_deg':25.,'T3070400_and_T3080401':'one binder heavy atom each below2A in fixed1IVO context'},indent=2))
